import { Injectable } from '@nestjs/common';
import axios, { AxiosInstance } from 'axios';
import { PokeResponse } from './interfaces/poke-response.interface';
import { PokemonService } from '../pokemon/pokemon.service';
import { Pokemon } from 'src/pokemon/entities/pokemon.entity';
import { Model } from 'mongoose';
import { CreatePokemonDto } from '../pokemon/dto/create-pokemon.dto';
import { InjectModel } from '@nestjs/mongoose';

@Injectable()
export class SeedService {

  private readonly axios : AxiosInstance = axios;
  private readonly pokemon : PokemonService;
  constructor(  
  @InjectModel(Pokemon.name)
  private readonly pokeModel:Model<Pokemon>,){
  
  } 
 // una opcion para no generar un insert cada vez que quiera crear un pokemon es realizarlo como compresa
  // async executeSeed() {
  //   await this.pokeModel.deleteMany({});

  //   const { data } = await axios.get<PokeResponse>('https://pokeapi.co/api/v2/pokemon?limit=50');

  //   const insertPromisesArray = [] ;

  //    data.results.forEach(async ({name,url})=>{

  //     const segments = url.split('/');
  //     const no:number = +segments[segments.length - 2];

  //     // const pokemon = await this.pokeModel.create({name,no});
  //     insertPromisesArray.push(this.pokeModel.create({name,no}))

  //   })
  //   const newArray = await Promise.all(insertPromisesArray);

  //   return `execute Seed`;
  //   // return data.results;

  // }// Generated by https://quicktype.io


   //otra opciones es realizar un solo insert
  async executeSeed() {
    await this.pokeModel.deleteMany({});

    const { data } = await axios.get<PokeResponse>('https://pokeapi.co/api/v2/pokemon?limit=50');

    const pokemonToInsert = [] ;

     data.results.forEach(async ({name,url})=>{

      const segments = url.split('/');
      const no:number = +segments[segments.length - 2];

      // const pokemon = await this.pokeModel.create({name,no});
      pokemonToInsert.push(this.pokeModel.create({name,no}))

    })
    await this.pokeModel.insertMany({pokemonToInsert});

    return `execute Seed`;
    // return data.results;

  }// Generated by https://quicktype.io


}